name: safework

services:
  db:
    image: mysql:8.4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: safework
      MYSQL_USER: safework_app
      MYSQL_PASSWORD: safework_app
    ports:
      - "3306:3306"
    volumes:
      - safework_db_data:/var/lib/mysql

volumes:
  safework_db_data:
